## This file is a general .xdc for the Basys3 rev B board
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

## Clock signal
set_property -dict {PACKAGE_PIN W5 IOSTANDARD LVCMOS33} [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]


## Switches
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {debug_state[0]}]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports {debug_state[1]}]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33} [get_ports {debug_state[2]}]
set_property -dict {PACKAGE_PIN W17 IOSTANDARD LVCMOS33} [get_ports {debug_state[3]}]
#set_property -dict { PACKAGE_PIN W15   IOSTANDARD LVCMOS33 } [get_ports {sw[4]}]
#set_property -dict { PACKAGE_PIN V15   IOSTANDARD LVCMOS33 } [get_ports {sw[5]}]
#set_property -dict { PACKAGE_PIN W14   IOSTANDARD LVCMOS33 } [get_ports {sw[6]}]
#set_property -dict { PACKAGE_PIN W13   IOSTANDARD LVCMOS33 } [get_ports {sw[7]}]
#set_property -dict { PACKAGE_PIN V2    IOSTANDARD LVCMOS33 } [get_ports {sw[8]}]
#set_property -dict { PACKAGE_PIN T3    IOSTANDARD LVCMOS33 } [get_ports {sw[9]}]
#set_property -dict { PACKAGE_PIN T2    IOSTANDARD LVCMOS33 } [get_ports {sw[10]}]
#set_property -dict { PACKAGE_PIN R3    IOSTANDARD LVCMOS33 } [get_ports {sw[11]}]
#set_property -dict { PACKAGE_PIN W2    IOSTANDARD LVCMOS33 } [get_ports {sw[12]}]
#set_property -dict { PACKAGE_PIN U1    IOSTANDARD LVCMOS33 } [get_ports {sw[13]}]
#set_property -dict { PACKAGE_PIN T1    IOSTANDARD LVCMOS33 } [get_ports {sw[14]}]
#set_property -dict { PACKAGE_PIN R2    IOSTANDARD LVCMOS33 } [get_ports {sw[15]}]


## LEDs
#set_property -dict { PACKAGE_PIN U16   IOSTANDARD LVCMOS33 } [get_ports {led[0]}]
#set_property -dict { PACKAGE_PIN E19   IOSTANDARD LVCMOS33 } [get_ports {led[1]}]
#set_property -dict { PACKAGE_PIN U19   IOSTANDARD LVCMOS33 } [get_ports {led[2]}]
#set_property -dict { PACKAGE_PIN V19   IOSTANDARD LVCMOS33 } [get_ports {led[3]}]
#set_property -dict { PACKAGE_PIN W18   IOSTANDARD LVCMOS33 } [get_ports {led[4]}]
#set_property -dict { PACKAGE_PIN U15   IOSTANDARD LVCMOS33 } [get_ports {led[5]}]
#set_property -dict { PACKAGE_PIN U14   IOSTANDARD LVCMOS33 } [get_ports {led[6]}]
#set_property -dict { PACKAGE_PIN V14   IOSTANDARD LVCMOS33 } [get_ports {led[7]}]
#set_property -dict { PACKAGE_PIN V13   IOSTANDARD LVCMOS33 } [get_ports {led[8]}]
#set_property -dict { PACKAGE_PIN V3    IOSTANDARD LVCMOS33 } [get_ports {led[9]}]
#set_property -dict { PACKAGE_PIN W3    IOSTANDARD LVCMOS33 } [get_ports {led[10]}]
#set_property -dict { PACKAGE_PIN U3    IOSTANDARD LVCMOS33 } [get_ports {led[11]}]
#set_property -dict { PACKAGE_PIN P3    IOSTANDARD LVCMOS33 } [get_ports {led[12]}]
#set_property -dict { PACKAGE_PIN N3    IOSTANDARD LVCMOS33 } [get_ports {led[13]}]
#set_property -dict { PACKAGE_PIN P1    IOSTANDARD LVCMOS33 } [get_ports {led[14]}]
#set_property -dict { PACKAGE_PIN L1    IOSTANDARD LVCMOS33 } [get_ports {led[15]}]


##7 Segment Display
#set_property -dict { PACKAGE_PIN W7   IOSTANDARD LVCMOS33 } [get_ports {seg[0]}]
#set_property -dict { PACKAGE_PIN W6   IOSTANDARD LVCMOS33 } [get_ports {seg[1]}]
#set_property -dict { PACKAGE_PIN U8   IOSTANDARD LVCMOS33 } [get_ports {seg[2]}]
#set_property -dict { PACKAGE_PIN V8   IOSTANDARD LVCMOS33 } [get_ports {seg[3]}]
#set_property -dict { PACKAGE_PIN U5   IOSTANDARD LVCMOS33 } [get_ports {seg[4]}]
#set_property -dict { PACKAGE_PIN V5   IOSTANDARD LVCMOS33 } [get_ports {seg[5]}]
#set_property -dict { PACKAGE_PIN U7   IOSTANDARD LVCMOS33 } [get_ports {seg[6]}]

#set_property -dict { PACKAGE_PIN V7   IOSTANDARD LVCMOS33 } [get_ports dp]

#set_property -dict { PACKAGE_PIN U2   IOSTANDARD LVCMOS33 } [get_ports {an[0]}]
#set_property -dict { PACKAGE_PIN U4   IOSTANDARD LVCMOS33 } [get_ports {an[1]}]
#set_property -dict { PACKAGE_PIN V4   IOSTANDARD LVCMOS33 } [get_ports {an[2]}]
#set_property -dict { PACKAGE_PIN W4   IOSTANDARD LVCMOS33 } [get_ports {an[3]}]


##Buttons
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports areset]
#set_property -dict { PACKAGE_PIN T18   IOSTANDARD LVCMOS33 } [get_ports btnU]
#set_property -dict { PACKAGE_PIN W19   IOSTANDARD LVCMOS33 } [get_ports btnL]
#set_property -dict { PACKAGE_PIN T17   IOSTANDARD LVCMOS33 } [get_ports btnR]
#set_property -dict { PACKAGE_PIN U17   IOSTANDARD LVCMOS33 } [get_ports btnD]


##Pmod Header JA
#set_property -dict { PACKAGE_PIN J1   IOSTANDARD LVCMOS33 } [get_ports {JA[0]}];#Sch name = JA1
#set_property -dict { PACKAGE_PIN L2   IOSTANDARD LVCMOS33 } [get_ports {JA[1]}];#Sch name = JA2
#set_property -dict { PACKAGE_PIN J2   IOSTANDARD LVCMOS33 } [get_ports {JA[2]}];#Sch name = JA3
#set_property -dict { PACKAGE_PIN G2   IOSTANDARD LVCMOS33 } [get_ports {JA[3]}];#Sch name = JA4
#set_property -dict { PACKAGE_PIN H1   IOSTANDARD LVCMOS33 } [get_ports {JA[4]}];#Sch name = JA7
#set_property -dict { PACKAGE_PIN K2   IOSTANDARD LVCMOS33 } [get_ports {JA[5]}];#Sch name = JA8
#set_property -dict { PACKAGE_PIN H2   IOSTANDARD LVCMOS33 } [get_ports {JA[6]}];#Sch name = JA9
#set_property -dict { PACKAGE_PIN G3   IOSTANDARD LVCMOS33 } [get_ports {JA[7]}];#Sch name = JA10

##Pmod Header JB
#set_property -dict { PACKAGE_PIN A14   IOSTANDARD LVCMOS33 } [get_ports {JB[0]}];#Sch name = JB1
#set_property -dict { PACKAGE_PIN A16   IOSTANDARD LVCMOS33 } [get_ports {JB[1]}];#Sch name = JB2
#set_property -dict { PACKAGE_PIN B15   IOSTANDARD LVCMOS33 } [get_ports {JB[2]}];#Sch name = JB3
#set_property -dict { PACKAGE_PIN B16   IOSTANDARD LVCMOS33 } [get_ports {JB[3]}];#Sch name = JB4
#set_property -dict { PACKAGE_PIN A15   IOSTANDARD LVCMOS33 } [get_ports {JB[4]}];#Sch name = JB7
#set_property -dict { PACKAGE_PIN A17   IOSTANDARD LVCMOS33 } [get_ports {JB[5]}];#Sch name = JB8
#set_property -dict { PACKAGE_PIN C15   IOSTANDARD LVCMOS33 } [get_ports {JB[6]}];#Sch name = JB9
#set_property -dict { PACKAGE_PIN C16   IOSTANDARD LVCMOS33 } [get_ports {JB[7]}];#Sch name = JB10

##Pmod Header JC
#set_property -dict { PACKAGE_PIN K17   IOSTANDARD LVCMOS33 } [get_ports {JC[0]}];#Sch name = JC1
#set_property -dict { PACKAGE_PIN M18   IOSTANDARD LVCMOS33 } [get_ports {JC[1]}];#Sch name = JC2
#set_property -dict { PACKAGE_PIN N17   IOSTANDARD LVCMOS33 } [get_ports {JC[2]}];#Sch name = JC3
#set_property -dict { PACKAGE_PIN P18   IOSTANDARD LVCMOS33 } [get_ports {JC[3]}];#Sch name = JC4
#set_property -dict { PACKAGE_PIN L17   IOSTANDARD LVCMOS33 } [get_ports {JC[4]}];#Sch name = JC7
#set_property -dict { PACKAGE_PIN M19   IOSTANDARD LVCMOS33 } [get_ports {JC[5]}];#Sch name = JC8
#set_property -dict { PACKAGE_PIN P17   IOSTANDARD LVCMOS33 } [get_ports {JC[6]}];#Sch name = JC9
#set_property -dict { PACKAGE_PIN R18   IOSTANDARD LVCMOS33 } [get_ports {JC[7]}];#Sch name = JC10

##Pmod Header JXADC
#set_property -dict { PACKAGE_PIN J3   IOSTANDARD LVCMOS33 } [get_ports {JXADC[0]}];#Sch name = XA1_P
#set_property -dict { PACKAGE_PIN L3   IOSTANDARD LVCMOS33 } [get_ports {JXADC[1]}];#Sch name = XA2_P
#set_property -dict { PACKAGE_PIN M2   IOSTANDARD LVCMOS33 } [get_ports {JXADC[2]}];#Sch name = XA3_P
#set_property -dict { PACKAGE_PIN N2   IOSTANDARD LVCMOS33 } [get_ports {JXADC[3]}];#Sch name = XA4_P
#set_property -dict { PACKAGE_PIN K3   IOSTANDARD LVCMOS33 } [get_ports {JXADC[4]}];#Sch name = XA1_N
#set_property -dict { PACKAGE_PIN M3   IOSTANDARD LVCMOS33 } [get_ports {JXADC[5]}];#Sch name = XA2_N
#set_property -dict { PACKAGE_PIN M1   IOSTANDARD LVCMOS33 } [get_ports {JXADC[6]}];#Sch name = XA3_N
#set_property -dict { PACKAGE_PIN N1   IOSTANDARD LVCMOS33 } [get_ports {JXADC[7]}];#Sch name = XA4_N


##VGA Connector
#set_property -dict { PACKAGE_PIN G19   IOSTANDARD LVCMOS33 } [get_ports {vgaRed[0]}]
#set_property -dict { PACKAGE_PIN H19   IOSTANDARD LVCMOS33 } [get_ports {vgaRed[1]}]
#set_property -dict { PACKAGE_PIN J19   IOSTANDARD LVCMOS33 } [get_ports {vgaRed[2]}]
#set_property -dict { PACKAGE_PIN N19   IOSTANDARD LVCMOS33 } [get_ports {vgaRed[3]}]
#set_property -dict { PACKAGE_PIN N18   IOSTANDARD LVCMOS33 } [get_ports {vgaBlue[0]}]
#set_property -dict { PACKAGE_PIN L18   IOSTANDARD LVCMOS33 } [get_ports {vgaBlue[1]}]
#set_property -dict { PACKAGE_PIN K18   IOSTANDARD LVCMOS33 } [get_ports {vgaBlue[2]}]
#set_property -dict { PACKAGE_PIN J18   IOSTANDARD LVCMOS33 } [get_ports {vgaBlue[3]}]
#set_property -dict { PACKAGE_PIN J17   IOSTANDARD LVCMOS33 } [get_ports {vgaGreen[0]}]
#set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33 } [get_ports {vgaGreen[1]}]
#set_property -dict { PACKAGE_PIN G17   IOSTANDARD LVCMOS33 } [get_ports {vgaGreen[2]}]
#set_property -dict { PACKAGE_PIN D17   IOSTANDARD LVCMOS33 } [get_ports {vgaGreen[3]}]
#set_property -dict { PACKAGE_PIN P19   IOSTANDARD LVCMOS33 } [get_ports Hsync]
#set_property -dict { PACKAGE_PIN R19   IOSTANDARD LVCMOS33 } [get_ports Vsync]


##USB-RS232 Interface
#set_property -dict { PACKAGE_PIN B18   IOSTANDARD LVCMOS33 } [get_ports RsRx]
#set_property -dict { PACKAGE_PIN A18   IOSTANDARD LVCMOS33 } [get_ports RsTx]


##USB HID (PS/2)
#set_property -dict { PACKAGE_PIN C17   IOSTANDARD LVCMOS33   PULLUP true } [get_ports PS2Clk]
#set_property -dict { PACKAGE_PIN B17   IOSTANDARD LVCMOS33   PULLUP true } [get_ports PS2Data]


##Quad SPI Flash
##Note that CCLK_0 cannot be placed in 7 series devices. You can access it using the
##STARTUPE2 primitive.
#set_property -dict { PACKAGE_PIN D18   IOSTANDARD LVCMOS33 } [get_ports {QspiDB[0]}]
#set_property -dict { PACKAGE_PIN D19   IOSTANDARD LVCMOS33 } [get_ports {QspiDB[1]}]
#set_property -dict { PACKAGE_PIN G18   IOSTANDARD LVCMOS33 } [get_ports {QspiDB[2]}]
#set_property -dict { PACKAGE_PIN F18   IOSTANDARD LVCMOS33 } [get_ports {QspiDB[3]}]
#set_property -dict { PACKAGE_PIN K19   IOSTANDARD LVCMOS33 } [get_ports QspiCSn]


## Configuration options, can be used for all designs
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

## SPI configuration mode options for QSPI boot, can be used for all designs
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

set_property LOC U18 [get_cells areset_IBUF_inst]
set_property LOC W5 [get_cells clk_IBUF_inst]
set_property BEL D6LUT [get_cells dm/ram_reg_0_63_0_0]
set_property BEL B6LUT [get_cells dm/ram_reg_0_63_11_11]
set_property BEL C6LUT [get_cells dm/ram_reg_0_63_12_12]
set_property BEL A6LUT [get_cells dm/ram_reg_0_63_10_10]
set_property BEL D6LUT [get_cells dm/ram_reg_0_63_13_13]
set_property BEL B6LUT [get_cells dm/ram_reg_0_63_15_15]
set_property BEL C6LUT [get_cells dm/ram_reg_0_63_16_16]
set_property BEL A6LUT [get_cells dm/ram_reg_0_63_14_14]
set_property BEL D6LUT [get_cells dm/ram_reg_0_63_17_17]
set_property BEL B6LUT [get_cells dm/ram_reg_0_63_19_19]
set_property BEL C6LUT [get_cells dm/ram_reg_0_63_1_1]
set_property BEL A6LUT [get_cells dm/ram_reg_0_63_18_18]
set_property BEL D6LUT [get_cells dm/ram_reg_0_63_20_20]
set_property BEL B6LUT [get_cells dm/ram_reg_0_63_22_22]
set_property BEL C6LUT [get_cells dm/ram_reg_0_63_23_23]
set_property BEL A6LUT [get_cells dm/ram_reg_0_63_21_21]
set_property BEL D6LUT [get_cells dm/ram_reg_0_63_24_24]
set_property BEL B6LUT [get_cells dm/ram_reg_0_63_26_26]
set_property BEL C6LUT [get_cells dm/ram_reg_0_63_27_27]
set_property BEL A6LUT [get_cells dm/ram_reg_0_63_25_25]
set_property BEL D6LUT [get_cells dm/ram_reg_0_63_28_28]
set_property BEL B6LUT [get_cells dm/ram_reg_0_63_2_2]
set_property BEL C6LUT [get_cells dm/ram_reg_0_63_30_30]
set_property BEL A6LUT [get_cells dm/ram_reg_0_63_29_29]
set_property BEL D6LUT [get_cells dm/ram_reg_0_63_31_31]
set_property BEL B6LUT [get_cells dm/ram_reg_0_63_4_4]
set_property BEL C6LUT [get_cells dm/ram_reg_0_63_5_5]
set_property BEL A6LUT [get_cells dm/ram_reg_0_63_3_3]
set_property BEL D6LUT [get_cells dm/ram_reg_0_63_6_6]
set_property BEL B6LUT [get_cells dm/ram_reg_0_63_8_8]
set_property BEL C6LUT [get_cells dm/ram_reg_0_63_9_9]
set_property BEL A6LUT [get_cells dm/ram_reg_0_63_7_7]
set_property BEL A6LUT [get_cells {rf/regs[7][31]_i_3}]
set_property BEL AFF [get_cells {pcu/PCR/PC_reg[0]}]
set_property BEL BFF [get_cells {pcu/PCR/PC_reg[1]}]
set_property BEL CFF [get_cells {pcu/PCR/PC_reg[2]}]
set_property BEL DFF [get_cells {pcu/PCR/PC_reg[3]}]
set_property BEL AFF [get_cells {pcu/PCR/PC_reg[4]}]
set_property BEL BFF [get_cells {pcu/PCR/PC_reg[5]}]
set_property BEL CFF [get_cells {pcu/PCR/PC_reg[6]}]
set_property BEL AFF [get_cells {rf/regs_reg[1][0]}]
set_property BEL AFF [get_cells {rf/regs_reg[1][10]}]
set_property BEL BFF [get_cells {rf/regs_reg[1][11]}]
set_property BEL BFF [get_cells {rf/regs_reg[1][12]}]
set_property BEL AFF [get_cells {rf/regs_reg[1][13]}]
set_property BEL BFF [get_cells {rf/regs_reg[1][14]}]
set_property BEL AFF [get_cells {rf/regs_reg[1][15]}]
set_property BEL BFF [get_cells {rf/regs_reg[1][16]}]
set_property BEL CFF [get_cells {rf/regs_reg[1][17]}]
set_property BEL DFF [get_cells {rf/regs_reg[1][18]}]
set_property BEL AFF [get_cells {rf/regs_reg[1][19]}]
set_property BEL AFF [get_cells {rf/regs_reg[1][1]}]
set_property BEL AFF [get_cells {rf/regs_reg[1][20]}]
set_property BEL BFF [get_cells {rf/regs_reg[1][21]}]
set_property BEL AFF [get_cells {rf/regs_reg[1][22]}]
set_property BEL AFF [get_cells {rf/regs_reg[1][23]}]
set_property BEL BFF [get_cells {rf/regs_reg[1][24]}]
set_property BEL AFF [get_cells {rf/regs_reg[1][25]}]
set_property BEL DFF [get_cells {rf/regs_reg[1][26]}]
set_property BEL BFF [get_cells {rf/regs_reg[1][27]}]
set_property BEL CFF [get_cells {rf/regs_reg[1][28]}]
set_property BEL CFF [get_cells {rf/regs_reg[1][29]}]
set_property BEL B5FF [get_cells {rf/regs_reg[1][2]}]
set_property BEL CFF [get_cells {rf/regs_reg[1][30]}]
set_property BEL BFF [get_cells {rf/regs_reg[1][31]}]
set_property BEL CFF [get_cells {rf/regs_reg[1][3]}]
set_property BEL DFF [get_cells {rf/regs_reg[1][4]}]
set_property BEL BFF [get_cells {rf/regs_reg[1][5]}]
set_property BEL BFF [get_cells {rf/regs_reg[1][6]}]
set_property BEL C5FF [get_cells {rf/regs_reg[1][7]}]
set_property BEL AFF [get_cells {rf/regs_reg[1][8]}]
set_property BEL D5FF [get_cells {rf/regs_reg[1][9]}]
set_property BEL AFF [get_cells {rf/regs_reg[2][0]}]
set_property BEL BFF [get_cells {rf/regs_reg[2][10]}]
set_property BEL AFF [get_cells {rf/regs_reg[2][11]}]
set_property BEL C5FF [get_cells {rf/regs_reg[2][12]}]
set_property BEL BFF [get_cells {rf/regs_reg[2][13]}]
set_property BEL BFF [get_cells {rf/regs_reg[2][14]}]
set_property BEL AFF [get_cells {rf/regs_reg[2][15]}]
set_property BEL AFF [get_cells {rf/regs_reg[2][16]}]
set_property BEL CFF [get_cells {rf/regs_reg[2][17]}]
set_property BEL DFF [get_cells {rf/regs_reg[2][18]}]
set_property BEL BFF [get_cells {rf/regs_reg[2][19]}]
set_property BEL CFF [get_cells {rf/regs_reg[2][1]}]
set_property BEL AFF [get_cells {rf/regs_reg[2][20]}]
set_property BEL AFF [get_cells {rf/regs_reg[2][21]}]
set_property BEL C5FF [get_cells {rf/regs_reg[2][22]}]
set_property BEL AFF [get_cells {rf/regs_reg[2][23]}]
set_property BEL BFF [get_cells {rf/regs_reg[2][24]}]
set_property BEL C5FF [get_cells {rf/regs_reg[2][25]}]
set_property BEL BFF [get_cells {rf/regs_reg[2][26]}]
set_property BEL CFF [get_cells {rf/regs_reg[2][27]}]
set_property BEL CFF [get_cells {rf/regs_reg[2][28]}]
set_property BEL DFF [get_cells {rf/regs_reg[2][29]}]
set_property BEL BFF [get_cells {rf/regs_reg[2][2]}]
set_property BEL DFF [get_cells {rf/regs_reg[2][30]}]
set_property BEL BFF [get_cells {rf/regs_reg[2][31]}]
set_property BEL CFF [get_cells {rf/regs_reg[2][3]}]
set_property BEL DFF [get_cells {rf/regs_reg[2][4]}]
set_property BEL DFF [get_cells {rf/regs_reg[2][5]}]
set_property BEL D5FF [get_cells {rf/regs_reg[2][6]}]
set_property BEL CFF [get_cells {rf/regs_reg[2][7]}]
set_property BEL AFF [get_cells {rf/regs_reg[2][8]}]
set_property BEL DFF [get_cells {rf/regs_reg[2][9]}]
set_property BEL BFF [get_cells {rf/regs_reg[3][0]}]
set_property BEL AFF [get_cells {rf/regs_reg[3][10]}]
set_property BEL AFF [get_cells {rf/regs_reg[3][11]}]
set_property BEL BFF [get_cells {rf/regs_reg[3][12]}]
set_property BEL BFF [get_cells {rf/regs_reg[3][13]}]
set_property BEL AFF [get_cells {rf/regs_reg[3][14]}]
set_property BEL BFF [get_cells {rf/regs_reg[3][15]}]
set_property BEL AFF [get_cells {rf/regs_reg[3][16]}]
set_property BEL BFF [get_cells {rf/regs_reg[3][17]}]
set_property BEL CFF [get_cells {rf/regs_reg[3][18]}]
set_property BEL BFF [get_cells {rf/regs_reg[3][19]}]
set_property BEL CFF [get_cells {rf/regs_reg[3][1]}]
set_property BEL AFF [get_cells {rf/regs_reg[3][20]}]
set_property BEL AFF [get_cells {rf/regs_reg[3][21]}]
set_property BEL BFF [get_cells {rf/regs_reg[3][22]}]
set_property BEL AFF [get_cells {rf/regs_reg[3][23]}]
set_property BEL BFF [get_cells {rf/regs_reg[3][24]}]
set_property BEL BFF [get_cells {rf/regs_reg[3][25]}]
set_property BEL BFF [get_cells {rf/regs_reg[3][26]}]
set_property BEL CFF [get_cells {rf/regs_reg[3][27]}]
set_property BEL DFF [get_cells {rf/regs_reg[3][28]}]
set_property BEL CFF [get_cells {rf/regs_reg[3][29]}]
set_property BEL BFF [get_cells {rf/regs_reg[3][2]}]
set_property BEL AFF [get_cells {rf/regs_reg[3][30]}]
set_property BEL AFF [get_cells {rf/regs_reg[3][31]}]
set_property BEL BFF [get_cells {rf/regs_reg[3][3]}]
set_property BEL BFF [get_cells {rf/regs_reg[3][4]}]
set_property BEL BFF [get_cells {rf/regs_reg[3][5]}]
set_property BEL DFF [get_cells {rf/regs_reg[3][6]}]
set_property BEL AFF [get_cells {rf/regs_reg[3][7]}]
set_property BEL DFF [get_cells {rf/regs_reg[3][8]}]
set_property BEL BFF [get_cells {rf/regs_reg[3][9]}]
set_property BEL AFF [get_cells {rf/regs_reg[4][0]}]
set_property BEL BFF [get_cells {rf/regs_reg[4][10]}]
set_property BEL AFF [get_cells {rf/regs_reg[4][11]}]
set_property BEL BFF [get_cells {rf/regs_reg[4][12]}]
set_property BEL BFF [get_cells {rf/regs_reg[4][13]}]
set_property BEL AFF [get_cells {rf/regs_reg[4][14]}]
set_property BEL AFF [get_cells {rf/regs_reg[4][15]}]
set_property BEL BFF [get_cells {rf/regs_reg[4][16]}]
set_property BEL BFF [get_cells {rf/regs_reg[4][17]}]
set_property BEL CFF [get_cells {rf/regs_reg[4][18]}]
set_property BEL BFF [get_cells {rf/regs_reg[4][19]}]
set_property BEL CFF [get_cells {rf/regs_reg[4][1]}]
set_property BEL AFF [get_cells {rf/regs_reg[4][20]}]
set_property BEL BFF [get_cells {rf/regs_reg[4][21]}]
set_property BEL DFF [get_cells {rf/regs_reg[4][22]}]
set_property BEL CFF [get_cells {rf/regs_reg[4][23]}]
set_property BEL BFF [get_cells {rf/regs_reg[4][24]}]
set_property BEL CFF [get_cells {rf/regs_reg[4][25]}]
set_property BEL BFF [get_cells {rf/regs_reg[4][26]}]
set_property BEL CFF [get_cells {rf/regs_reg[4][27]}]
set_property BEL DFF [get_cells {rf/regs_reg[4][28]}]
set_property BEL BFF [get_cells {rf/regs_reg[4][29]}]
set_property BEL CFF [get_cells {rf/regs_reg[4][2]}]
set_property BEL AFF [get_cells {rf/regs_reg[4][30]}]
set_property BEL BFF [get_cells {rf/regs_reg[4][31]}]
set_property BEL CFF [get_cells {rf/regs_reg[4][3]}]
set_property BEL AFF [get_cells {rf/regs_reg[4][4]}]
set_property BEL AFF [get_cells {rf/regs_reg[4][5]}]
set_property BEL BFF [get_cells {rf/regs_reg[4][6]}]
set_property BEL AFF [get_cells {rf/regs_reg[4][7]}]
set_property BEL DFF [get_cells {rf/regs_reg[4][8]}]
set_property BEL BFF [get_cells {rf/regs_reg[4][9]}]
set_property BEL AFF [get_cells {rf/regs_reg[5][0]}]
set_property BEL BFF [get_cells {rf/regs_reg[5][10]}]
set_property BEL CFF [get_cells {rf/regs_reg[5][11]}]
set_property BEL AFF [get_cells {rf/regs_reg[5][12]}]
set_property BEL BFF [get_cells {rf/regs_reg[5][13]}]
set_property BEL BFF [get_cells {rf/regs_reg[5][14]}]
set_property BEL CFF [get_cells {rf/regs_reg[5][15]}]
set_property BEL AFF [get_cells {rf/regs_reg[5][16]}]
set_property BEL CFF [get_cells {rf/regs_reg[5][17]}]
set_property BEL CFF [get_cells {rf/regs_reg[5][18]}]
set_property BEL AFF [get_cells {rf/regs_reg[5][19]}]
set_property BEL AFF [get_cells {rf/regs_reg[5][1]}]
set_property BEL AFF [get_cells {rf/regs_reg[5][20]}]
set_property BEL BFF [get_cells {rf/regs_reg[5][21]}]
set_property BEL BFF [get_cells {rf/regs_reg[5][22]}]
set_property BEL BFF [get_cells {rf/regs_reg[5][23]}]
set_property BEL CFF [get_cells {rf/regs_reg[5][24]}]
set_property BEL CFF [get_cells {rf/regs_reg[5][25]}]
set_property BEL BFF [get_cells {rf/regs_reg[5][26]}]
set_property BEL BFF [get_cells {rf/regs_reg[5][27]}]
set_property BEL CFF [get_cells {rf/regs_reg[5][28]}]
set_property BEL CFF [get_cells {rf/regs_reg[5][29]}]
set_property BEL DFF [get_cells {rf/regs_reg[5][2]}]
set_property BEL BFF [get_cells {rf/regs_reg[5][30]}]
set_property BEL AFF [get_cells {rf/regs_reg[5][31]}]
set_property BEL DFF [get_cells {rf/regs_reg[5][3]}]
set_property BEL BFF [get_cells {rf/regs_reg[5][4]}]
set_property BEL B5FF [get_cells {rf/regs_reg[5][5]}]
set_property BEL BFF [get_cells {rf/regs_reg[5][6]}]
set_property BEL CFF [get_cells {rf/regs_reg[5][7]}]
set_property BEL DFF [get_cells {rf/regs_reg[5][8]}]
set_property BEL DFF [get_cells {rf/regs_reg[5][9]}]
set_property BEL AFF [get_cells {rf/regs_reg[6][0]}]
set_property BEL BFF [get_cells {rf/regs_reg[6][10]}]
set_property BEL CFF [get_cells {rf/regs_reg[6][11]}]
set_property BEL AFF [get_cells {rf/regs_reg[6][12]}]
set_property BEL AFF [get_cells {rf/regs_reg[6][13]}]
set_property BEL AFF [get_cells {rf/regs_reg[6][14]}]
set_property BEL DFF [get_cells {rf/regs_reg[6][15]}]
set_property BEL BFF [get_cells {rf/regs_reg[6][16]}]
set_property BEL BFF [get_cells {rf/regs_reg[6][17]}]
set_property BEL BFF [get_cells {rf/regs_reg[6][18]}]
set_property BEL AFF [get_cells {rf/regs_reg[6][19]}]
set_property BEL A5FF [get_cells {rf/regs_reg[6][1]}]
set_property BEL AFF [get_cells {rf/regs_reg[6][20]}]
set_property BEL AFF [get_cells {rf/regs_reg[6][21]}]
set_property BEL CFF [get_cells {rf/regs_reg[6][22]}]
set_property BEL BFF [get_cells {rf/regs_reg[6][23]}]
set_property BEL BFF [get_cells {rf/regs_reg[6][24]}]
set_property BEL B5FF [get_cells {rf/regs_reg[6][25]}]
set_property BEL CFF [get_cells {rf/regs_reg[6][26]}]
set_property BEL BFF [get_cells {rf/regs_reg[6][27]}]
set_property BEL DFF [get_cells {rf/regs_reg[6][28]}]
set_property BEL BFF [get_cells {rf/regs_reg[6][29]}]
set_property BEL CFF [get_cells {rf/regs_reg[6][2]}]
set_property BEL CFF [get_cells {rf/regs_reg[6][30]}]
set_property BEL AFF [get_cells {rf/regs_reg[6][31]}]
set_property BEL DFF [get_cells {rf/regs_reg[6][3]}]
set_property BEL BFF [get_cells {rf/regs_reg[6][4]}]
set_property BEL B5FF [get_cells {rf/regs_reg[6][5]}]
set_property BEL DFF [get_cells {rf/regs_reg[6][6]}]
set_property BEL BFF [get_cells {rf/regs_reg[6][7]}]
set_property BEL BFF [get_cells {rf/regs_reg[6][8]}]
set_property BEL CFF [get_cells {rf/regs_reg[6][9]}]
set_property BEL AFF [get_cells {rf/regs_reg[7][0]}]
set_property BEL AFF [get_cells {rf/regs_reg[7][10]}]
set_property BEL BFF [get_cells {rf/regs_reg[7][11]}]
set_property BEL BFF [get_cells {rf/regs_reg[7][12]}]
set_property BEL AFF [get_cells {rf/regs_reg[7][13]}]
set_property BEL BFF [get_cells {rf/regs_reg[7][14]}]
set_property BEL BFF [get_cells {rf/regs_reg[7][15]}]
set_property BEL BFF [get_cells {rf/regs_reg[7][16]}]
set_property BEL BFF [get_cells {rf/regs_reg[7][17]}]
set_property BEL CFF [get_cells {rf/regs_reg[7][18]}]
set_property BEL AFF [get_cells {rf/regs_reg[7][19]}]
set_property BEL CFF [get_cells {rf/regs_reg[7][1]}]
set_property BEL AFF [get_cells {rf/regs_reg[7][20]}]
set_property BEL AFF [get_cells {rf/regs_reg[7][21]}]
set_property BEL CFF [get_cells {rf/regs_reg[7][22]}]
set_property BEL CFF [get_cells {rf/regs_reg[7][23]}]
set_property BEL DFF [get_cells {rf/regs_reg[7][24]}]
set_property BEL AFF [get_cells {rf/regs_reg[7][25]}]
set_property BEL BFF [get_cells {rf/regs_reg[7][26]}]
set_property BEL BFF [get_cells {rf/regs_reg[7][27]}]
set_property BEL CFF [get_cells {rf/regs_reg[7][28]}]
set_property BEL CFF [get_cells {rf/regs_reg[7][29]}]
set_property BEL DFF [get_cells {rf/regs_reg[7][2]}]
set_property BEL CFF [get_cells {rf/regs_reg[7][30]}]
set_property BEL AFF [get_cells {rf/regs_reg[7][31]}]
set_property BEL DFF [get_cells {rf/regs_reg[7][3]}]
set_property BEL CFF [get_cells {rf/regs_reg[7][4]}]
set_property BEL DFF [get_cells {rf/regs_reg[7][5]}]
set_property BEL DFF [get_cells {rf/regs_reg[7][6]}]
set_property BEL BFF [get_cells {rf/regs_reg[7][7]}]
set_property BEL BFF [get_cells {rf/regs_reg[7][8]}]
set_property BEL CFF [get_cells {rf/regs_reg[7][9]}]
set_property LOC SLICE_X0Y13 [get_cells {rf/regs[7][31]_i_3}]
set_property LOC BUFGCTRL_X0Y0 [get_cells clk_IBUF_BUFG_inst]
set_property LOC SLICE_X9Y3 [get_cells {pcu/PCR/PC_reg[0]}]
set_property LOC SLICE_X9Y3 [get_cells {pcu/PCR/PC_reg[1]}]
set_property LOC SLICE_X9Y3 [get_cells {pcu/PCR/PC_reg[2]}]
set_property LOC SLICE_X9Y3 [get_cells {pcu/PCR/PC_reg[3]}]
set_property LOC SLICE_X9Y4 [get_cells {pcu/PCR/PC_reg[4]}]
set_property LOC SLICE_X9Y4 [get_cells {pcu/PCR/PC_reg[5]}]
set_property LOC SLICE_X9Y4 [get_cells {pcu/PCR/PC_reg[6]}]
set_property LOC SLICE_X6Y0 [get_cells {rf/regs_reg[1][0]}]
set_property LOC SLICE_X4Y2 [get_cells {rf/regs_reg[1][10]}]
set_property LOC SLICE_X4Y2 [get_cells {rf/regs_reg[1][11]}]
set_property LOC SLICE_X9Y7 [get_cells {rf/regs_reg[1][12]}]
set_property LOC SLICE_X12Y1 [get_cells {rf/regs_reg[1][13]}]
set_property LOC SLICE_X12Y1 [get_cells {rf/regs_reg[1][14]}]
set_property LOC SLICE_X5Y3 [get_cells {rf/regs_reg[1][15]}]
set_property LOC SLICE_X15Y6 [get_cells {rf/regs_reg[1][16]}]
set_property LOC SLICE_X12Y1 [get_cells {rf/regs_reg[1][17]}]
set_property LOC SLICE_X12Y1 [get_cells {rf/regs_reg[1][18]}]
set_property LOC SLICE_X3Y3 [get_cells {rf/regs_reg[1][19]}]
set_property LOC SLICE_X2Y1 [get_cells {rf/regs_reg[1][1]}]
set_property LOC SLICE_X7Y10 [get_cells {rf/regs_reg[1][20]}]
set_property LOC SLICE_X7Y10 [get_cells {rf/regs_reg[1][21]}]
set_property LOC SLICE_X14Y1 [get_cells {rf/regs_reg[1][22]}]
set_property LOC SLICE_X11Y10 [get_cells {rf/regs_reg[1][23]}]
set_property LOC SLICE_X9Y8 [get_cells {rf/regs_reg[1][24]}]
set_property LOC SLICE_X8Y10 [get_cells {rf/regs_reg[1][25]}]
set_property LOC SLICE_X9Y8 [get_cells {rf/regs_reg[1][26]}]
set_property LOC SLICE_X10Y6 [get_cells {rf/regs_reg[1][27]}]
set_property LOC SLICE_X9Y7 [get_cells {rf/regs_reg[1][28]}]
set_property LOC SLICE_X10Y6 [get_cells {rf/regs_reg[1][29]}]
set_property LOC SLICE_X12Y1 [get_cells {rf/regs_reg[1][2]}]
set_property LOC SLICE_X15Y6 [get_cells {rf/regs_reg[1][30]}]
set_property LOC SLICE_X3Y3 [get_cells {rf/regs_reg[1][31]}]
set_property LOC SLICE_X3Y3 [get_cells {rf/regs_reg[1][3]}]
set_property LOC SLICE_X3Y3 [get_cells {rf/regs_reg[1][4]}]
set_property LOC SLICE_X2Y1 [get_cells {rf/regs_reg[1][5]}]
set_property LOC SLICE_X14Y1 [get_cells {rf/regs_reg[1][6]}]
set_property LOC SLICE_X12Y1 [get_cells {rf/regs_reg[1][7]}]
set_property LOC SLICE_X4Y8 [get_cells {rf/regs_reg[1][8]}]
set_property LOC SLICE_X12Y1 [get_cells {rf/regs_reg[1][9]}]
set_property LOC SLICE_X3Y0 [get_cells {rf/regs_reg[2][0]}]
set_property LOC SLICE_X3Y0 [get_cells {rf/regs_reg[2][10]}]
set_property LOC SLICE_X3Y2 [get_cells {rf/regs_reg[2][11]}]
set_property LOC SLICE_X8Y6 [get_cells {rf/regs_reg[2][12]}]
set_property LOC SLICE_X11Y5 [get_cells {rf/regs_reg[2][13]}]
set_property LOC SLICE_X13Y1 [get_cells {rf/regs_reg[2][14]}]
set_property LOC SLICE_X6Y3 [get_cells {rf/regs_reg[2][15]}]
set_property LOC SLICE_X12Y8 [get_cells {rf/regs_reg[2][16]}]
set_property LOC SLICE_X13Y1 [get_cells {rf/regs_reg[2][17]}]
set_property LOC SLICE_X13Y1 [get_cells {rf/regs_reg[2][18]}]
set_property LOC SLICE_X3Y5 [get_cells {rf/regs_reg[2][19]}]
set_property LOC SLICE_X3Y0 [get_cells {rf/regs_reg[2][1]}]
set_property LOC SLICE_X7Y14 [get_cells {rf/regs_reg[2][20]}]
set_property LOC SLICE_X5Y9 [get_cells {rf/regs_reg[2][21]}]
set_property LOC SLICE_X13Y1 [get_cells {rf/regs_reg[2][22]}]
set_property LOC SLICE_X12Y9 [get_cells {rf/regs_reg[2][23]}]
set_property LOC SLICE_X12Y9 [get_cells {rf/regs_reg[2][24]}]
set_property LOC SLICE_X4Y11 [get_cells {rf/regs_reg[2][25]}]
set_property LOC SLICE_X12Y8 [get_cells {rf/regs_reg[2][26]}]
set_property LOC SLICE_X11Y5 [get_cells {rf/regs_reg[2][27]}]
set_property LOC SLICE_X12Y8 [get_cells {rf/regs_reg[2][28]}]
set_property LOC SLICE_X11Y5 [get_cells {rf/regs_reg[2][29]}]
set_property LOC SLICE_X12Y3 [get_cells {rf/regs_reg[2][2]}]
set_property LOC SLICE_X12Y8 [get_cells {rf/regs_reg[2][30]}]
set_property LOC SLICE_X3Y2 [get_cells {rf/regs_reg[2][31]}]
set_property LOC SLICE_X3Y2 [get_cells {rf/regs_reg[2][3]}]
set_property LOC SLICE_X3Y2 [get_cells {rf/regs_reg[2][4]}]
set_property LOC SLICE_X3Y0 [get_cells {rf/regs_reg[2][5]}]
set_property LOC SLICE_X13Y1 [get_cells {rf/regs_reg[2][6]}]
set_property LOC SLICE_X12Y3 [get_cells {rf/regs_reg[2][7]}]
set_property LOC SLICE_X3Y8 [get_cells {rf/regs_reg[2][8]}]
set_property LOC SLICE_X12Y3 [get_cells {rf/regs_reg[2][9]}]
set_property LOC SLICE_X8Y0 [get_cells {rf/regs_reg[3][0]}]
set_property LOC SLICE_X4Y0 [get_cells {rf/regs_reg[3][10]}]
set_property LOC SLICE_X2Y2 [get_cells {rf/regs_reg[3][11]}]
set_property LOC SLICE_X8Y7 [get_cells {rf/regs_reg[3][12]}]
set_property LOC SLICE_X13Y4 [get_cells {rf/regs_reg[3][13]}]
set_property LOC SLICE_X10Y0 [get_cells {rf/regs_reg[3][14]}]
set_property LOC SLICE_X7Y2 [get_cells {rf/regs_reg[3][15]}]
set_property LOC SLICE_X13Y7 [get_cells {rf/regs_reg[3][16]}]
set_property LOC SLICE_X10Y0 [get_cells {rf/regs_reg[3][17]}]
set_property LOC SLICE_X10Y0 [get_cells {rf/regs_reg[3][18]}]
set_property LOC SLICE_X4Y5 [get_cells {rf/regs_reg[3][19]}]
set_property LOC SLICE_X7Y2 [get_cells {rf/regs_reg[3][1]}]
set_property LOC SLICE_X6Y11 [get_cells {rf/regs_reg[3][20]}]
set_property LOC SLICE_X6Y6 [get_cells {rf/regs_reg[3][21]}]
set_property LOC SLICE_X14Y3 [get_cells {rf/regs_reg[3][22]}]
set_property LOC SLICE_X10Y11 [get_cells {rf/regs_reg[3][23]}]
set_property LOC SLICE_X10Y11 [get_cells {rf/regs_reg[3][24]}]
set_property LOC SLICE_X6Y11 [get_cells {rf/regs_reg[3][25]}]
set_property LOC SLICE_X11Y7 [get_cells {rf/regs_reg[3][26]}]
set_property LOC SLICE_X8Y7 [get_cells {rf/regs_reg[3][27]}]
set_property LOC SLICE_X11Y7 [get_cells {rf/regs_reg[3][28]}]
set_property LOC SLICE_X13Y4 [get_cells {rf/regs_reg[3][29]}]
set_property LOC SLICE_X13Y5 [get_cells {rf/regs_reg[3][2]}]
set_property LOC SLICE_X12Y7 [get_cells {rf/regs_reg[3][30]}]
set_property LOC SLICE_X4Y3 [get_cells {rf/regs_reg[3][31]}]
set_property LOC SLICE_X8Y3 [get_cells {rf/regs_reg[3][3]}]
set_property LOC SLICE_X4Y3 [get_cells {rf/regs_reg[3][4]}]
set_property LOC SLICE_X4Y0 [get_cells {rf/regs_reg[3][5]}]
set_property LOC SLICE_X10Y0 [get_cells {rf/regs_reg[3][6]}]
set_property LOC SLICE_X14Y2 [get_cells {rf/regs_reg[3][7]}]
set_property LOC SLICE_X4Y9 [get_cells {rf/regs_reg[3][8]}]
set_property LOC SLICE_X14Y2 [get_cells {rf/regs_reg[3][9]}]
set_property LOC SLICE_X5Y0 [get_cells {rf/regs_reg[4][0]}]
set_property LOC SLICE_X5Y0 [get_cells {rf/regs_reg[4][10]}]
set_property LOC SLICE_X2Y4 [get_cells {rf/regs_reg[4][11]}]
set_property LOC SLICE_X8Y9 [get_cells {rf/regs_reg[4][12]}]
set_property LOC SLICE_X11Y3 [get_cells {rf/regs_reg[4][13]}]
set_property LOC SLICE_X9Y1 [get_cells {rf/regs_reg[4][14]}]
set_property LOC SLICE_X7Y0 [get_cells {rf/regs_reg[4][15]}]
set_property LOC SLICE_X11Y6 [get_cells {rf/regs_reg[4][16]}]
set_property LOC SLICE_X9Y1 [get_cells {rf/regs_reg[4][17]}]
set_property LOC SLICE_X11Y3 [get_cells {rf/regs_reg[4][18]}]
set_property LOC SLICE_X5Y5 [get_cells {rf/regs_reg[4][19]}]
set_property LOC SLICE_X5Y0 [get_cells {rf/regs_reg[4][1]}]
set_property LOC SLICE_X6Y10 [get_cells {rf/regs_reg[4][20]}]
set_property LOC SLICE_X6Y8 [get_cells {rf/regs_reg[4][21]}]
set_property LOC SLICE_X11Y3 [get_cells {rf/regs_reg[4][22]}]
set_property LOC SLICE_X8Y9 [get_cells {rf/regs_reg[4][23]}]
set_property LOC SLICE_X10Y10 [get_cells {rf/regs_reg[4][24]}]
set_property LOC SLICE_X6Y8 [get_cells {rf/regs_reg[4][25]}]
set_property LOC SLICE_X10Y7 [get_cells {rf/regs_reg[4][26]}]
set_property LOC SLICE_X10Y7 [get_cells {rf/regs_reg[4][27]}]
set_property LOC SLICE_X10Y7 [get_cells {rf/regs_reg[4][28]}]
set_property LOC SLICE_X10Y4 [get_cells {rf/regs_reg[4][29]}]
set_property LOC SLICE_X10Y4 [get_cells {rf/regs_reg[4][2]}]
set_property LOC SLICE_X13Y8 [get_cells {rf/regs_reg[4][30]}]
set_property LOC SLICE_X2Y4 [get_cells {rf/regs_reg[4][31]}]
set_property LOC SLICE_X9Y1 [get_cells {rf/regs_reg[4][3]}]
set_property LOC SLICE_X1Y4 [get_cells {rf/regs_reg[4][4]}]
set_property LOC SLICE_X1Y0 [get_cells {rf/regs_reg[4][5]}]
set_property LOC SLICE_X9Y0 [get_cells {rf/regs_reg[4][6]}]
set_property LOC SLICE_X12Y4 [get_cells {rf/regs_reg[4][7]}]
set_property LOC SLICE_X6Y8 [get_cells {rf/regs_reg[4][8]}]
set_property LOC SLICE_X12Y4 [get_cells {rf/regs_reg[4][9]}]
set_property LOC SLICE_X3Y1 [get_cells {rf/regs_reg[5][0]}]
set_property LOC SLICE_X3Y1 [get_cells {rf/regs_reg[5][10]}]
set_property LOC SLICE_X3Y1 [get_cells {rf/regs_reg[5][11]}]
set_property LOC SLICE_X11Y8 [get_cells {rf/regs_reg[5][12]}]
set_property LOC SLICE_X11Y2 [get_cells {rf/regs_reg[5][13]}]
set_property LOC SLICE_X10Y3 [get_cells {rf/regs_reg[5][14]}]
set_property LOC SLICE_X13Y3 [get_cells {rf/regs_reg[5][15]}]
set_property LOC SLICE_X12Y6 [get_cells {rf/regs_reg[5][16]}]
set_property LOC SLICE_X11Y2 [get_cells {rf/regs_reg[5][17]}]
set_property LOC SLICE_X10Y3 [get_cells {rf/regs_reg[5][18]}]
set_property LOC SLICE_X5Y4 [get_cells {rf/regs_reg[5][19]}]
set_property LOC SLICE_X2Y0 [get_cells {rf/regs_reg[5][1]}]
set_property LOC SLICE_X7Y12 [get_cells {rf/regs_reg[5][20]}]
set_property LOC SLICE_X6Y9 [get_cells {rf/regs_reg[5][21]}]
set_property LOC SLICE_X13Y3 [get_cells {rf/regs_reg[5][22]}]
set_property LOC SLICE_X11Y9 [get_cells {rf/regs_reg[5][23]}]
set_property LOC SLICE_X11Y9 [get_cells {rf/regs_reg[5][24]}]
set_property LOC SLICE_X6Y9 [get_cells {rf/regs_reg[5][25]}]
set_property LOC SLICE_X11Y8 [get_cells {rf/regs_reg[5][26]}]
set_property LOC SLICE_X9Y6 [get_cells {rf/regs_reg[5][27]}]
set_property LOC SLICE_X11Y8 [get_cells {rf/regs_reg[5][28]}]
set_property LOC SLICE_X9Y6 [get_cells {rf/regs_reg[5][29]}]
set_property LOC SLICE_X10Y3 [get_cells {rf/regs_reg[5][2]}]
set_property LOC SLICE_X12Y6 [get_cells {rf/regs_reg[5][30]}]
set_property LOC SLICE_X2Y3 [get_cells {rf/regs_reg[5][31]}]
set_property LOC SLICE_X3Y1 [get_cells {rf/regs_reg[5][3]}]
set_property LOC SLICE_X2Y3 [get_cells {rf/regs_reg[5][4]}]
set_property LOC SLICE_X3Y1 [get_cells {rf/regs_reg[5][5]}]
set_property LOC SLICE_X12Y0 [get_cells {rf/regs_reg[5][6]}]
set_property LOC SLICE_X12Y0 [get_cells {rf/regs_reg[5][7]}]
set_property LOC SLICE_X6Y9 [get_cells {rf/regs_reg[5][8]}]
set_property LOC SLICE_X12Y0 [get_cells {rf/regs_reg[5][9]}]
set_property LOC SLICE_X6Y1 [get_cells {rf/regs_reg[6][0]}]
set_property LOC SLICE_X4Y1 [get_cells {rf/regs_reg[6][10]}]
set_property LOC SLICE_X4Y1 [get_cells {rf/regs_reg[6][11]}]
set_property LOC SLICE_X9Y10 [get_cells {rf/regs_reg[6][12]}]
set_property LOC SLICE_X12Y2 [get_cells {rf/regs_reg[6][13]}]
set_property LOC SLICE_X11Y1 [get_cells {rf/regs_reg[6][14]}]
set_property LOC SLICE_X4Y1 [get_cells {rf/regs_reg[6][15]}]
set_property LOC SLICE_X14Y6 [get_cells {rf/regs_reg[6][16]}]
set_property LOC SLICE_X11Y1 [get_cells {rf/regs_reg[6][17]}]
set_property LOC SLICE_X9Y2 [get_cells {rf/regs_reg[6][18]}]
set_property LOC SLICE_X4Y4 [get_cells {rf/regs_reg[6][19]}]
set_property LOC SLICE_X4Y1 [get_cells {rf/regs_reg[6][1]}]
set_property LOC SLICE_X7Y11 [get_cells {rf/regs_reg[6][20]}]
set_property LOC SLICE_X6Y7 [get_cells {rf/regs_reg[6][21]}]
set_property LOC SLICE_X11Y1 [get_cells {rf/regs_reg[6][22]}]
set_property LOC SLICE_X9Y10 [get_cells {rf/regs_reg[6][23]}]
set_property LOC SLICE_X10Y9 [get_cells {rf/regs_reg[6][24]}]
set_property LOC SLICE_X5Y11 [get_cells {rf/regs_reg[6][25]}]
set_property LOC SLICE_X10Y9 [get_cells {rf/regs_reg[6][26]}]
set_property LOC SLICE_X9Y5 [get_cells {rf/regs_reg[6][27]}]
set_property LOC SLICE_X10Y9 [get_cells {rf/regs_reg[6][28]}]
set_property LOC SLICE_X12Y5 [get_cells {rf/regs_reg[6][29]}]
set_property LOC SLICE_X9Y2 [get_cells {rf/regs_reg[6][2]}]
set_property LOC SLICE_X14Y6 [get_cells {rf/regs_reg[6][30]}]
set_property LOC SLICE_X3Y4 [get_cells {rf/regs_reg[6][31]}]
set_property LOC SLICE_X9Y2 [get_cells {rf/regs_reg[6][3]}]
set_property LOC SLICE_X3Y4 [get_cells {rf/regs_reg[6][4]}]
set_property LOC SLICE_X4Y1 [get_cells {rf/regs_reg[6][5]}]
set_property LOC SLICE_X11Y1 [get_cells {rf/regs_reg[6][6]}]
set_property LOC SLICE_X12Y2 [get_cells {rf/regs_reg[6][7]}]
set_property LOC SLICE_X8Y8 [get_cells {rf/regs_reg[6][8]}]
set_property LOC SLICE_X12Y2 [get_cells {rf/regs_reg[6][9]}]
set_property LOC SLICE_X7Y1 [get_cells {rf/regs_reg[7][0]}]
set_property LOC SLICE_X5Y1 [get_cells {rf/regs_reg[7][10]}]
set_property LOC SLICE_X5Y1 [get_cells {rf/regs_reg[7][11]}]
set_property LOC SLICE_X9Y9 [get_cells {rf/regs_reg[7][12]}]
set_property LOC SLICE_X10Y5 [get_cells {rf/regs_reg[7][13]}]
set_property LOC SLICE_X11Y4 [get_cells {rf/regs_reg[7][14]}]
set_property LOC SLICE_X7Y1 [get_cells {rf/regs_reg[7][15]}]
set_property LOC SLICE_X13Y6 [get_cells {rf/regs_reg[7][16]}]
set_property LOC SLICE_X11Y0 [get_cells {rf/regs_reg[7][17]}]
set_property LOC SLICE_X11Y0 [get_cells {rf/regs_reg[7][18]}]
set_property LOC SLICE_X6Y5 [get_cells {rf/regs_reg[7][19]}]
set_property LOC SLICE_X7Y1 [get_cells {rf/regs_reg[7][1]}]
set_property LOC SLICE_X6Y12 [get_cells {rf/regs_reg[7][20]}]
set_property LOC SLICE_X5Y8 [get_cells {rf/regs_reg[7][21]}]
set_property LOC SLICE_X11Y4 [get_cells {rf/regs_reg[7][22]}]
set_property LOC SLICE_X9Y9 [get_cells {rf/regs_reg[7][23]}]
set_property LOC SLICE_X9Y9 [get_cells {rf/regs_reg[7][24]}]
set_property LOC SLICE_X8Y12 [get_cells {rf/regs_reg[7][25]}]
set_property LOC SLICE_X10Y8 [get_cells {rf/regs_reg[7][26]}]
set_property LOC SLICE_X10Y5 [get_cells {rf/regs_reg[7][27]}]
set_property LOC SLICE_X10Y8 [get_cells {rf/regs_reg[7][28]}]
set_property LOC SLICE_X10Y5 [get_cells {rf/regs_reg[7][29]}]
set_property LOC SLICE_X11Y4 [get_cells {rf/regs_reg[7][2]}]
set_property LOC SLICE_X13Y6 [get_cells {rf/regs_reg[7][30]}]
set_property LOC SLICE_X1Y3 [get_cells {rf/regs_reg[7][31]}]
set_property LOC SLICE_X7Y1 [get_cells {rf/regs_reg[7][3]}]
set_property LOC SLICE_X5Y1 [get_cells {rf/regs_reg[7][4]}]
set_property LOC SLICE_X5Y1 [get_cells {rf/regs_reg[7][5]}]
set_property LOC SLICE_X11Y0 [get_cells {rf/regs_reg[7][6]}]
set_property LOC SLICE_X13Y2 [get_cells {rf/regs_reg[7][7]}]
set_property LOC SLICE_X5Y8 [get_cells {rf/regs_reg[7][8]}]
set_property LOC SLICE_X13Y2 [get_cells {rf/regs_reg[7][9]}]
set_property FIXED_ROUTE { { IOB_IBUF0 RIOI_I0 RIOI_ILOGIC0_D IOI_ILOGIC0_O RIOI_I2GCLK_TOP0 HCLK_CMT_CK_IN0 CLK_HROW_BOT_R_CK_BUFG_CASCO0 CLK_BUFG_BUFGCTRL0_I0 }  } [get_nets clk_IBUF]
set_property FIXED_ROUTE { { CLK_BUFG_BUFGCTRL0_O CLK_BUFG_CK_GCLK0 CLK_BUFG_REBUF_R_CK_GCLK0_BOT CLK_HROW_CK_MUX_OUT_L8 CLK_HROW_CK_HCLK_OUT_L8 CLK_HROW_CK_BUFHCLK_L8  { <8>HCLK_LEAF_CLK_B_BOTL5  { <17>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { <20>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { <21>GCLK_L_B11_WEST CLK_L0 CLBLL_L_CLK }   { <22>GCLK_L_B11_WEST CLK_L0 CLBLL_L_CLK }   { <25>GCLK_L_B11_WEST CLK_L0 CLBLL_L_CLK }   { <21>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <22>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <23>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <24>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }  <25>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <7>HCLK_LEAF_CLK_B_BOTL5  { <11>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { <16>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <17>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <18>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <19>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <20>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <21>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <22>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <23>GCLK_L_B11_WEST CLK_L1 CLBLL_LL_CLK }   { <14>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <16>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <17>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <20>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <21>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <22>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <24>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <25>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <13>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <14>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <15>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <23>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <24>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }  <25>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <6>HCLK_LEAF_CLK_B_BOTL5  { <20>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { <13>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <15>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <16>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <17>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <18>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <19>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <21>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <22>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <23>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <24>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }  <25>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <5>HCLK_LEAF_CLK_B_BOTL5  { <14>GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <15>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <16>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <17>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <18>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <19>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <20>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <21>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <22>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <23>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <24>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }  <25>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }  <4>HCLK_LEAF_CLK_B_BOTL5  { <16>GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <22>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <23>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <24>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <25>GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <17>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <18>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <19>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <20>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <21>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <22>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <23>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <24>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }  <19>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }  } [get_nets clk_IBUF_BUFG]
set_property FIXED_ROUTE { { IOB_IBUF1 LIOI_I1 LIOI_ILOGIC1_D IOI_ILOGIC1_O IOI_LOGIC_OUTS18_0 INT_INTERFACE_LOGIC_OUTS_L18 EE2BEG0 IMUX_L1 CLBLL_LL_A3 }  } [get_nets areset_IBUF]
